import { Player, StaffMember } from "@/types";

export const PLAYERS: Player[] = [
  // ================= Porteros (4) =================
  {
    id: "cesar-samudio",
    name: "César Samudio",
    fullName: "César Augusto Samudio Murillo",
    number: 23,
    position: "Portero",
    category: "goalkeeper",
    image: "/assets/players/cesar_samudio.png",
    actionImage: "/assets/players/cesar-samudio-action.png",
    birthDate: "1994-02-25",
    birthPlace: "Panamá, Panamá",
    nationality: "Panameña",
    height: "1.86 m",
    weight: "82 kg",
    preferredFoot: "Derecho",
    joinedDate: "2023-01-15",
    isCaptain: true,
    stats: {
      matchesPlayed: 36,
      cleanSheets: 14,
      minutesPlayed: 3240,
      yellowCards: 2,
      redCards: 0,
    },
    attributes: {
      reflexes: 87,
      handling: 82,
      diving: 84,
      positioning: 85,
      kicking: 78,
      speed: 55,
    },
    bio: "Llegó al club en 2023 y rápidamente se convirtió en uno de los referentes indiscutibles y capitán del equipo. Con grandes reflejos y un liderazgo natural bajo los tres palos, ha sido clave para mantener el arco en cero en múltiples partidos.",
    quote: "Vestir esta camiseta es una responsabilidad inmensa. En el Yankel, cada partido lo jugamos con el corazón en la mano por esta hinchada.",
  },
  {
    id: "humberto-juarez",
    name: "Humberto Juárez",
    fullName: "Humberto Juárez",
    number: 31,
    position: "Portero",
    category: "goalkeeper",
    birthDate: "2007-04-12",
    birthPlace: "Tegucigalpa, Honduras",
    image: "/assets/players/humberto-juarez.png",
    actionImage: "/assets/players/humberto-juarez-action.png",
    nationality: "Hondureña",
    height: "1.85 m",
    weight: "78 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-06-01",
    stats: {
      matchesPlayed: 2,
      cleanSheets: 1,
      minutesPlayed: 180,
      yellowCards: 0,
      redCards: 0,
    },
    attributes: {
      reflexes: 74,
      handling: 71,
      diving: 73,
      positioning: 70,
      kicking: 68,
      speed: 52,
    },
    bio: "Joven guardameta formado en las reservas del club, con una gran proyección de cara al futuro. Destaca por sus reflejos rápidos en tiros a corta distancia.",
  },
  {
    id: "jonathan-rougier",
    name: "Jonathan Rougier",
    fullName: "Jonathan Felipe Rougier",
    number: 1,
    position: "Portero",
    category: "goalkeeper",
    birthDate: "1987-10-29",
    birthPlace: "Villa Elisa, Argentina",
    image: "/assets/players/jonathan-rougier.png",
    actionImage: "/assets/players/jonathan-rougier-action.png",
    nationality: "Hondureña",
    height: "1.89 m",
    weight: "84 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-07-01",
    stats: {
      matchesPlayed: 180,
      cleanSheets: 70,
      minutesPlayed: 16200,
      yellowCards: 8,
      redCards: 1,
    },
    attributes: {
      reflexes: 83,
      handling: 85,
      diving: 81,
      positioning: 86,
      kicking: 88,
      speed: 48,
    },
    bio: "Experimentado portero de amplia trayectoria en el fútbol nacional. Aporta liderazgo, seguridad y una excelente técnica en el juego aéreo y en la salida con los pies.",
  },

  // ================= Defensas (9) =================
  {
    id: "javier-rivera",
    name: "Javier Rivera",
    fullName: "Javier de la Cruz Rivera",
    number: 4,
    position: "Defensa",
    category: "defender",
    image: "/assets/players/javier-rivera.png",
    actionImage: "/assets/players/javier-rivera-action.png",
    birthDate: "1998-03-16",
    birthPlace: "Colón, Panamá",
    nationality: "Panameña",
    height: "1.85 m",
    weight: "78 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-01-05",
    stats: {
      matchesPlayed: 32,
      goals: 2,
      assists: 1,
      minutesPlayed: 2880,
      yellowCards: 6,
      redCards: 1,
    },
    attributes: {
      pace: 75,
      shooting: 45,
      passing: 68,
      dribbling: 60,
      defending: 82,
      physical: 84,
    },
    bio: "Defensa central fuerte y con excelente anticipación. Su potencia física y buen juego aéreo lo hacen una muralla en la zona defensiva del Monstruo Verde.",
    quote: "Atrás no pasa nada. Cada balón dividido se pelea como si fuera la última final.",
  },
  {
    id: "jonathan-paz",
    name: "Jonathan Paz",
    fullName: "Jonathan Francisco Paz Hernandez",
    number: 15,
    position: "Defensa",
    category: "defender",
    birthDate: "1995-06-18",
    birthPlace: "Tocoa, Honduras",
    image: "/assets/players/jonathan-paz.png",
    actionImage: "/assets/players/jonathan-paz-action.png",
    nationality: "Hondureña",
    height: "1.82 m",
    weight: "76 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-07-01",
    stats: {
      matchesPlayed: 24,
      goals: 1,
      assists: 0,
      minutesPlayed: 2160,
      yellowCards: 4,
      redCards: 0,
    },
    attributes: {
      pace: 73,
      shooting: 42,
      passing: 65,
      dribbling: 58,
      defending: 80,
      physical: 82,
    },
    bio: "Defensa central de gran experiencia en la liga nacional, conocido por su fuerte marca y capacidad de anticipar los ataques rivales.",
  },
  {
    id: "kenny-bodden",
    name: "Kenny Bodden",
    fullName: "Kenny Bodden",
    number: 3,
    position: "Defensa",
    category: "defender",
    image: "/assets/players/kenny-bodden.png",
    actionImage: "/assets/players/kenny-bodden-action.png",
    birthDate: "1999-05-12",
    birthPlace: "La Ceiba, Honduras",
    nationality: "Hondureña",
    height: "1.86 m",
    weight: "80 kg",
    preferredFoot: "Derecho",
    joinedDate: "2023-07-01",
    stats: {
      matchesPlayed: 18,
      goals: 0,
      assists: 0,
      minutesPlayed: 1350,
      yellowCards: 5,
      redCards: 1,
    },
    attributes: {
      pace: 68,
      shooting: 38,
      passing: 60,
      dribbling: 52,
      defending: 77,
      physical: 80,
    },
    bio: "Marcador central de gran fortaleza física, especialista en los duelos individuales terrestres y aéreos. Siempre concentrado en la marca.",
    quote: "El orden y la comunicación atrás son innegociables.",
  },
  {
    id: "henry-figueroa",
    name: "Henry Figueroa",
    fullName: "Henry Figueroa Alonso",
    number: 2,
    position: "Defensa",
    category: "defender",
    birthDate: "1992-12-28",
    birthPlace: "Santa Fe, Honduras",
    image: "/assets/players/henry-figueroa.png",
    actionImage: "/assets/players/henry-figueroa-action.png",
    nationality: "Hondureña",
    height: "1.84 m",
    weight: "77 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-06-15",
    stats: {
      matchesPlayed: 15,
      goals: 0,
      assists: 1,
      minutesPlayed: 1250,
      yellowCards: 4,
      redCards: 0,
    },
    attributes: {
      pace: 72,
      shooting: 46,
      passing: 64,
      dribbling: 61,
      defending: 81,
      physical: 83,
    },
    bio: "Defensa central con mucha garra y fuerza en la marca, posee un excelente liderazgo en la línea defensiva.",
  },
  {
    id: "jose-aguilera",
    name: "José Aguilera",
    fullName: "José Aguilera",
    number: 19,
    position: "Defensa",
    category: "defender",
    birthDate: "2000-01-20",
    birthPlace: "San Pedro Sula, Honduras",
    image: "/assets/players/jose-aguilera.png",
    actionImage: "/assets/players/jose-aguilera-action.png",
    nationality: "Hondureña",
    height: "1.75 m",
    weight: "70 kg",
    preferredFoot: "Izquierdo",
    joinedDate: "2024-01-10",
    stats: {
      matchesPlayed: 14,
      goals: 0,
      assists: 2,
      minutesPlayed: 1050,
      yellowCards: 3,
      redCards: 0,
    },
    attributes: {
      pace: 80,
      shooting: 51,
      passing: 69,
      dribbling: 71,
      defending: 73,
      physical: 72,
    },
    bio: "Lateral izquierdo de buena velocidad y vocación tanto para defender como para sumarse al ataque por su banda.",
  },
  {
    id: "javier-arriaga",
    name: "Javier Arriaga",
    fullName: "Javier Antonio Arriaga Chirinos",
    number: 14,
    position: "Defensa",
    category: "defender",
    image: "/assets/players/javier-arriaga.png",
    actionImage: "/assets/players/javier-arriaga-action.png",
    birthDate: "2004-08-01",
    birthPlace: "El Progreso, Honduras",
    nationality: "Hondureña",
    height: "1.74 m",
    weight: "68 kg",
    preferredFoot: "Izquierdo",
    joinedDate: "2022-07-01",
    stats: {
      matchesPlayed: 28,
      goals: 1,
      assists: 4,
      minutesPlayed: 2320,
      yellowCards: 4,
      redCards: 0,
    },
    attributes: {
      pace: 84,
      shooting: 58,
      passing: 74,
      dribbling: 76,
      defending: 75,
      physical: 70,
    },
    bio: "Joven lateral izquierdo con gran proyección ofensiva y velocidad. Posee un excelente centro y una gran resistencia para recorrer la banda de principio a fin.",
    quote: "Mi sueño siempre fue jugar aquí. Dejo todo por esta banda, atacando y defendiendo con el alma.",
  },
  {
    id: "jonathan-bueso",
    name: "Jonathan Bueso",
    fullName: "Jonathan Bueso",
    number: 20,
    position: "Defensa",
    category: "defender",
    birthDate: "2006-08-20",
    birthPlace: "San Pedro Sula, Honduras",
    image: "/assets/players/jonathan-bueso.png",
    actionImage: "/assets/players/jonathan-bueso-action.png",
    nationality: "Hondureña",
    height: "1.72 m",
    weight: "65 kg",
    preferredFoot: "Derecho",
    joinedDate: "2023-01-15",
    stats: {
      matchesPlayed: 8,
      goals: 0,
      assists: 0,
      minutesPlayed: 450,
      yellowCards: 1,
      redCards: 0,
    },
    attributes: {
      pace: 79,
      shooting: 48,
      passing: 66,
      dribbling: 68,
      defending: 71,
      physical: 68,
    },
    bio: "Joven defensor derecho con una excelente proyección. Destaca por su agilidad y compromiso táctico.",
  },
  {
    id: "andre-orellana",
    name: "André Orellana",
    fullName: "André Estefan Orellana Gómez",
    number: 6,
    position: "Defensa",
    category: "defender",
    birthDate: "2002-02-24",
    birthPlace: "San Pedro Sula, Honduras",
    image: "/assets/players/andre-orellana.png",
    actionImage: "/assets/players/andre-orellana-action.png",
    nationality: "Hondureña",
    height: "1.83 m",
    weight: "77 kg",
    preferredFoot: "Derecho",
    joinedDate: "2023-01-10",
    stats: {
      matchesPlayed: 22,
      goals: 1,
      assists: 0,
      minutesPlayed: 1850,
      yellowCards: 4,
      redCards: 1,
    },
    attributes: {
      pace: 74,
      shooting: 41,
      passing: 63,
      dribbling: 59,
      defending: 78,
      physical: 80,
    },
    bio: "Defensor central o lateral con gran agresividad deportiva y firmeza en los duelos individuales.",
  },

  // ================= Mediocampistas (10) =================
  {
    id: "tomas-sorto",
    name: "Tomas Sorto",
    fullName: "Tomas Sorto",
    number: 8,
    position: "Mediocampista",
    category: "midfielder",
    birthDate: "2003-01-15",
    birthPlace: "Yoro, Honduras",
    image: "/assets/players/tomas-sorto.png",
    actionImage: "/assets/players/tomas-sorto-action.png",
    nationality: "Hondureña",
    height: "1.76 m",
    weight: "72 kg",
    preferredFoot: "Derecho",
    joinedDate: "2023-06-15",
    stats: {
      matchesPlayed: 28,
      goals: 1,
      assists: 2,
      minutesPlayed: 2140,
      yellowCards: 5,
      redCards: 0,
    },
    attributes: {
      pace: 73,
      shooting: 60,
      passing: 75,
      dribbling: 71,
      defending: 77,
      physical: 76,
    },
    bio: "Pivote defensivo con buen posicionamiento y capacidad para cortar el juego del rival en la mitad del campo.",
  },
  {
    id: "damin-ramirez",
    name: "Damín Ramírez",
    fullName: "Damín Ramírez Arriaga",
    number: 10,
    position: "Mediocampista",
    category: "midfielder",
    image: "/assets/players/damin-ramirez.png",
    actionImage: "/assets/players/damin-ramirez-action.png",
    birthDate: "1993-01-15",
    birthPlace: "Yoro, Honduras",
    nationality: "Hondureña",
    height: "1.70 m",
    weight: "69 kg",
    preferredFoot: "Derecho",
    joinedDate: "2022-06-15",
    stats: {
      matchesPlayed: 33,
      goals: 5,
      assists: 7,
      minutesPlayed: 2640,
      yellowCards: 4,
      redCards: 0,
    },
    attributes: {
      pace: 72,
      shooting: 76,
      passing: 84,
      dribbling: 78,
      defending: 64,
      physical: 70,
    },
    bio: "Mediocampista mixto de exquisita técnica y disparo de larga distancia. Se encarga de la distribución y los tiros libres. Es el metrónomo del fútbol verdolaga.",
    quote: "La precisión y la paciencia abren los cerrojos más difíciles en el campo de juego.",
  },
  {
    id: "francisco-martinez",
    name: "Francisco Martínez",
    fullName: "Francisco Javier Martínez Ruíz",
    number: 5,
    position: "Mediocampista",
    category: "midfielder",
    image: "/assets/players/francisco-martinez.png",
    actionImage: "/assets/players/francisco-martinez-action.png",
    birthDate: "1992-10-29",
    birthPlace: "Santa Elena, Honduras",
    nationality: "Hondureña",
    height: "1.78 m",
    weight: "74 kg",
    preferredFoot: "Derecho",
    joinedDate: "2022-08-01",
    stats: {
      matchesPlayed: 34,
      goals: 3,
      assists: 2,
      minutesPlayed: 2890,
      yellowCards: 9,
      redCards: 0,
    },
    attributes: {
      pace: 70,
      shooting: 65,
      passing: 78,
      dribbling: 70,
      defending: 81,
      physical: 85,
    },
    bio: "Popularmente conocido como 'El Chelo', su ascenso meteórico desde el fútbol amateur hasta la selección nacional y Marathón inspiró a todo el país. Es el pulmón del mediocampo, infatigable en la recuperación y con buen trato de balón.",
    quote: "Nunca dejes de creer. Con trabajo duro, humildad y fe, no hay sueños imposibles.",
  },
  {
    id: "yairo-moreno",
    name: "Yairo Moreno",
    fullName: "Yairo Yesid Moreno Berrío",
    number: 18,
    position: "Mediocampista",
    category: "midfielder",
    birthDate: "1995-04-04",
    birthPlace: "Necoclí, Colombia",
    image: "/assets/players/yairo-moreno.png",
    actionImage: "/assets/players/yairo-moreno-action.png",
    nationality: "Colombiana",
    height: "1.83 m",
    weight: "78 kg",
    preferredFoot: "Izquierdo",
    joinedDate: "2024-07-01",
    stats: {
      matchesPlayed: 180,
      goals: 25,
      assists: 30,
      minutesPlayed: 15200,
      yellowCards: 15,
      redCards: 2,
    },
    attributes: {
      pace: 85,
      shooting: 78,
      passing: 82,
      dribbling: 84,
      defending: 70,
      physical: 79,
    },
    bio: "Fichaje estelar colombiano de jerarquía internacional. Ex jugador de equipos de la Liga MX, aporta tremenda velocidad, regate, pase y pegada desde la banda izquierda.",
  },
  {
    id: "isaac-castillo",
    name: "Isaac Castillo",
    fullName: "Isaac Edgardo Castillo Díaz",
    number: 7,
    position: "Mediocampista",
    category: "midfielder",
    image: "/assets/players/isaac-castillo.png",
    actionImage: "/assets/players/isaac-castillo-action.png",
    birthDate: "2003-05-24",
    birthPlace: "San Pedro Sula, Honduras",
    nationality: "Hondureña",
    height: "1.72 m",
    weight: "66 kg",
    preferredFoot: "Derecho",
    joinedDate: "2021-01-01",
    stats: {
      matchesPlayed: 31,
      goals: 4,
      assists: 6,
      minutesPlayed: 1980,
      yellowCards: 3,
      redCards: 0,
    },
    attributes: {
      pace: 78,
      shooting: 72,
      passing: 82,
      dribbling: 84,
      defending: 55,
      physical: 62,
    },
    bio: "Una de las joyas de las fuerzas básicas del club. Mediocampista ofensivo muy creativo, con un regate en espacio corto sobresaliente y excelente visión para asistir a los delanteros.",
    quote: "Llevar la número 10 de este club histórico es un orgullo y un reto que asumo con alegría y pasión.",
  },
  {
    id: "alexy-vega",
    name: "Alexy Vega",
    fullName: "Alexy Noel Vega Orellana",
    number: 17,
    position: "Mediocampista",
    category: "midfielder",
    image: "/assets/players/alexy-vega.png",
    actionImage: "/assets/players/alexy-vega-action.png",
    birthDate: "1996-09-16",
    birthPlace: "Jutiapa, Honduras",
    nationality: "Hondureña",
    height: "1.75 m",
    weight: "70 kg",
    preferredFoot: "Izquierdo",
    joinedDate: "2024-01-01",
    stats: {
      matchesPlayed: 35,
      goals: 18,
      assists: 9,
      minutesPlayed: 2950,
      yellowCards: 5,
      redCards: 0,
    },
    attributes: {
      pace: 88,
      shooting: 86,
      passing: 80,
      dribbling: 85,
      defending: 42,
      physical: 74,
    },
    bio: "Extremo desequilibrante con un disparo temible de pierna zurda y gran capacidad goleadora. Nombrado jugador de la temporada tras guiar al equipo ofensivamente con goles de tiro libre, larga distancia y jugadas individuales.",
    quote: "Tomo el balón pensando en la portería. La alegría del gol es lo que nos mueve cada fin de semana.",
  },
  {
    id: "odin-ramos",
    name: "Odín Ramos",
    fullName: "Odín Ramos",
    number: 21,
    position: "Mediocampista",
    category: "midfielder",
    birthDate: "2003-08-20",
    birthPlace: "San Pedro Sula, Honduras",
    image: "/assets/players/odin-ramos.png",
    actionImage: "/assets/players/odin-ramos-action.png",
    nationality: "Hondureña",
    height: "1.73 m",
    weight: "67 kg",
    preferredFoot: "Derecho",
    joinedDate: "2021-06-01",
    stats: {
      matchesPlayed: 25,
      goals: 3,
      assists: 4,
      minutesPlayed: 1450,
      yellowCards: 2,
      redCards: 0,
    },
    attributes: {
      pace: 82,
      shooting: 70,
      passing: 78,
      dribbling: 81,
      defending: 48,
      physical: 61,
    },
    bio: "Mediocentro ofensivo con gran regate y habilidad de pase en corto para romper cerrojos defensivos.",
  },
  // ================= Delanteros (11) =================
  {
    id: "carlos-perez",
    name: "Carlos Perez",
    fullName: "Carlos Pérez",
    number: 27,
    position: "Delantero",
    category: "forward",
    birthDate: "1999-12-15",
    birthPlace: "San Pedro Sula, Honduras",
    image: "/assets/players/carlos-perez.png",
    actionImage: "/assets/players/carlos-perez-action.png",
    nationality: "Hondureña",
    height: "1.76 m",
    weight: "71 kg",
    preferredFoot: "Izquierdo",
    joinedDate: "2023-12-15",
    stats: {
      matchesPlayed: 14,
      goals: 2,
      assists: 1,
      minutesPlayed: 750,
      yellowCards: 1,
      redCards: 0,
    },
    attributes: {
      pace: 82,
      shooting: 72,
      passing: 68,
      dribbling: 74,
      defending: 35,
      physical: 68,
    },
    bio: "Extremo izquierdo con buena velocidad y buen remate de pierna zurda.",
  },
  {
    id: "cristian-sacaza",
    name: "Cristian Sacaza",
    fullName: "Cristian Sacaza",
    number: 30,
    position: "Delantero",
    category: "forward",
    birthDate: "1998-10-18",
    birthPlace: "San Pedro Sula, Honduras",
    image: "/assets/players/cristian-sacaza.png",
    actionImage: "/assets/players/cristian-sacaza-action.png",
    nationality: "Hondureña",
    height: "1.75 m",
    weight: "70 kg",
    preferredFoot: "Izquierdo",
    joinedDate: "2023-06-01",
    stats: {
      matchesPlayed: 25,
      goals: 4,
      assists: 3,
      minutesPlayed: 1040,
      yellowCards: 1,
      redCards: 0,
    },
    attributes: {
      pace: 87,
      shooting: 73,
      passing: 69,
      dribbling: 80,
      defending: 38,
      physical: 60,
    },
    bio: "Extremo izquierdo muy veloz y habilidoso, gran revulsivo para cambiar la dinámica del partido.",
  },
  {
    id: "cesar-sevilla",
    name: "Cesar Sevilla",
    fullName: "Cesar Sevilla",
    number: 41,
    position: "Delantero",
    category: "forward",
    birthDate: "2005-04-12",
    birthPlace: "Yoro, Honduras",
    image: "/assets/players/cesar-sevilla.png",
    actionImage: "/assets/players/cesar-sevilla-action.png",
    nationality: "Hondureña",
    height: "1.72 m",
    weight: "66 kg",
    preferredFoot: "Izquierdo",
    joinedDate: "2023-01-10",
    stats: {
      matchesPlayed: 10,
      goals: 0,
      assists: 1,
      minutesPlayed: 450,
      yellowCards: 2,
      redCards: 0,
    },
    attributes: {
      pace: 78,
      shooting: 65,
      passing: 62,
      dribbling: 70,
      defending: 32,
      physical: 58,
    },
    bio: "Joven extremo izquierdo con buen balance ofensivo y táctico.",
  },
  {
    id: "alberth-elis",
    name: "Alberth Elis",
    fullName: "Alberth Josué Elis Martínez",
    number: 9,
    position: "Delantero",
    category: "forward",
    birthDate: "1996-02-12",
    birthPlace: "San Pedro Sula, Honduras",
    image: "/assets/players/alberth-elis.png",
    actionImage: "/assets/players/alberth-elis-action.png",
    nationality: "Hondureña",
    height: "1.80 m",
    weight: "79 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-07-01",
    stats: {
      matchesPlayed: 250,
      goals: 90,
      assists: 45,
      minutesPlayed: 21500,
      yellowCards: 20,
      redCards: 3,
    },
    attributes: {
      pace: 92,
      shooting: 84,
      passing: 75,
      dribbling: 82,
      defending: 35,
      physical: 85,
    },
    bio: "Fichaje bomba y estrella de jerarquía de la Furia Verde. Con amplia trayectoria en Europa y la Selección Nacional, 'La Panterita' es una amenaza ofensiva implacable gracias a su increíble velocidad y fuerza.",
  },
  {
    id: "yeison-mejia",
    name: "Yeison Mejía",
    fullName: "Yeison Fernando Mejía",
    number: 12,
    position: "Delantero",
    category: "forward",
    birthDate: "1998-01-18",
    birthPlace: "San Pedro Sula, Honduras",
    image: "/assets/players/yeison-mejia.png",
    actionImage: "/assets/players/yeison-mejia-action.png",
    nationality: "Hondureña",
    height: "1.74 m",
    weight: "72 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-07-01",
    stats: {
      matchesPlayed: 32,
      goals: 6,
      assists: 5,
      minutesPlayed: 2180,
      yellowCards: 4,
      redCards: 0,
    },
    attributes: {
      pace: 82,
      shooting: 74,
      passing: 70,
      dribbling: 78,
      defending: 42,
      physical: 72,
    },
    bio: "Extremo derecho desequilibrante, veloz y con una gran pegada de media distancia.",
  },
  {
    id: "nicolas-messiniti",
    name: "Nicolás Messiniti",
    fullName: "Nicolás Messiniti León",
    number: 11,
    position: "Delantero",
    category: "forward",
    image: "/assets/players/nicolas-messiniti.png",
    actionImage: "/assets/players/nicolas-messiniti-action.png",
    birthDate: "1996-04-13",
    birthPlace: "Buenos Aires, Argentina",
    nationality: "Argentina",
    height: "1.80 m",
    weight: "80 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-01-15",
    stats: {
      matchesPlayed: 32,
      goals: 12,
      assists: 3,
      minutesPlayed: 2210,
      yellowCards: 3,
      redCards: 0,
    },
    attributes: {
      pace: 74,
      shooting: 82,
      passing: 68,
      dribbling: 72,
      defending: 40,
      physical: 83,
    },
    bio: "Delantero centro de gran movilidad y olfato goleador. Destaca por su frialdad frente a la portería y juego asociativo.",
  },
  {
    id: "nayrobi-vargas",
    name: "Nayrobi Vargas",
    fullName: "Nayrobi Vargas",
    number: 99,
    position: "Delantero",
    category: "forward",
    birthDate: "2006-02-18",
    birthPlace: "San Pedro Sula, Honduras",
    image: "/assets/players/nayrobi-vargas.png",
    actionImage: "/assets/players/nayrobi-vargas-action.png",
    nationality: "Hondureña",
    height: "1.87 m",
    weight: "85 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-06-15",
    stats: {
      matchesPlayed: 15,
      goals: 4,
      assists: 2,
      minutesPlayed: 980,
      yellowCards: 2,
      redCards: 0,
    },
    attributes: {
      pace: 78,
      shooting: 75,
      passing: 65,
      dribbling: 72,
      defending: 40,
      physical: 82,
    },
    bio: "Promisorio delantero centro hondureño que llega desde el fútbol alemán. Gran físico, potencia y zancada aérea.",
  },
];

export const STAFF: StaffMember[] = [
  {
    id: "hernan-medina",
    name: "Hernán Medina",
    role: "Director Técnico",
    nationality: "Argentina",
    joinedDate: "2024-01-01",
    image: "/assets/players/hernan-medina.webp",
    bio: "Conocido como 'La Tota', el estratega cordobés llegó para plasmar una identidad de juego ofensiva, intensa y dinámica. Subcampeón con el club en su primer torneo, busca consolidar el proyecto rumbo a la décima copa.",
  },
  {
    id: "leonardo-torres",
    name: "Leonardo Torres",
    role: "Asistente Técnico",
    nationality: "Argentina",
    joinedDate: "2024-01-01",
    bio: "Mano derecha del Director Técnico, encargado del análisis táctico de los rivales y de planificar el trabajo táctico diario.",
  },
  {
    id: "juan-obelar",
    name: "Juan Obelar",
    role: "Preparador de Porteros",
    nationality: "Uruguaya",
    joinedDate: "2023-06-01",
    bio: "Ex-guardameta histórico de Marathón y muy querido por la afición. Hoy vuelca su experiencia preparando al máximo nivel a César Samudio y los jóvenes del arco verdolaga.",
  },
];
