import { Player, StaffMember } from "@/types";

export const PLAYERS: Player[] = [
  // ================= Porteros =================
  {
    id: "cesar-samudio",
    name: "César Samudio",
    fullName: "César Augusto Samudio Murillo",
    number: 23,
    position: "Portero",
    category: "goalkeeper",
    image: "/assets/players/cesar_samudio.png",
    actionImage: "/assets/players/cesar-samudio-action.png",
    birthDate: "1994-02-25",
    birthPlace: "Panamá, Panamá",
    nationality: "Panameña",
    height: "1.86 m",
    weight: "82 kg",
    preferredFoot: "Derecho",
    joinedDate: "2023-01-15",
    isCaptain: true,
    stats: {
      matchesPlayed: 36,
      cleanSheets: 14,
      minutesPlayed: 3240,
      yellowCards: 2,
      redCards: 0,
    },
    attributes: {
      reflexes: 87,
      handling: 82,
      diving: 84,
      positioning: 85,
      kicking: 78,
      speed: 55,
    },
    bio: "Llegó al club en 2023 y rápidamente se convirtió en uno de los referentes indiscutibles y capitán del equipo. Con grandes reflejos y un liderazgo natural bajo los tres palos, ha sido clave para mantener el arco en cero en múltiples partidos.",
    quote: "Vestir esta camiseta es una responsabilidad inmensa. En el Yankel, cada partido lo jugamos con el corazón en la mano por esta hinchada.",
  },
  {
    id: "luis-ortiz",
    name: "Luis Ortiz",
    fullName: "Luis Jovany Ortiz Solano",
    number: 1,
    position: "Portero",
    category: "goalkeeper",
    image: "/assets/players/luis-ortiz.webp",
    birthDate: "1997-11-20",
    birthPlace: "San Pedro Sula, Honduras",
    nationality: "Hondureña",
    height: "1.88 m",
    weight: "80 kg",
    preferredFoot: "Derecho",
    joinedDate: "2021-06-01",
    stats: {
      matchesPlayed: 4,
      cleanSheets: 1,
      minutesPlayed: 360,
      yellowCards: 0,
      redCards: 0,
    },
    attributes: {
      reflexes: 76,
      handling: 74,
      diving: 78,
      positioning: 72,
      kicking: 70,
      speed: 52,
    },
    bio: "Portero de grandes condiciones físicas y excelente juego aéreo. Siempre listo para defender el marco verdolaga cuando el equipo lo requiere, mostrando gran profesionalismo.",
    quote: "La constancia en el trabajo diario es lo que te mantiene listo para cuando llegue la oportunidad.",
  },

  // ================= Defensas =================
  {
    id: "javier-rivera",
    name: "Javier Rivera",
    fullName: "Javier de la Cruz Rivera",
    number: 14,
    position: "Defensa",
    category: "defender",
    image: "/assets/players/javier-rivera.webp",
    birthDate: "1998-03-16",
    birthPlace: "Colón, Panamá",
    nationality: "Panameña",
    height: "1.85 m",
    weight: "78 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-01-05",
    stats: {
      matchesPlayed: 32,
      goals: 2,
      assists: 1,
      minutesPlayed: 2880,
      yellowCards: 6,
      redCards: 1,
    },
    attributes: {
      pace: 75,
      shooting: 45,
      passing: 68,
      dribbling: 60,
      defending: 82,
      physical: 84,
    },
    bio: "Defensa central fuerte y con excelente anticipación. Su potencia física y buen juego aéreo lo hacen una muralla en la zona defensiva del Monstruo Verde.",
    quote: "Atrás no pasa nada. Cada balón dividido se pelea como si fuera la última final.",
  },
  {
    id: "javier-arriaga",
    name: "Javier Arriaga",
    fullName: "Javier Antonio Arriaga Chirinos",
    number: 17,
    position: "Defensa",
    category: "defender",
    image: "/assets/players/javier-arriaga.webp",
    birthDate: "2004-08-01",
    birthPlace: "El Progreso, Honduras",
    nationality: "Hondureña",
    height: "1.74 m",
    weight: "68 kg",
    preferredFoot: "Izquierdo",
    joinedDate: "2022-07-01",
    stats: {
      matchesPlayed: 28,
      goals: 1,
      assists: 4,
      minutesPlayed: 2320,
      yellowCards: 4,
      redCards: 0,
    },
    attributes: {
      pace: 84,
      shooting: 58,
      passing: 74,
      dribbling: 76,
      defending: 75,
      physical: 70,
    },
    bio: "Joven lateral izquierdo con gran proyección ofensiva y velocidad. Posee un excelente centro y una gran resistencia para recorrer la banda de principio a fin.",
    quote: "Mi sueño siempre fue jugar aquí. Dejo todo por esta banda, atacando y defendiendo con el alma.",
  },
  {
    id: "felix-crisanto",
    name: "Félix Crisanto",
    fullName: "Félix Joan Crisanto Casildo",
    number: 2,
    position: "Defensa",
    category: "defender",
    image: "/assets/players/felix-crisanto.webp",
    birthDate: "1990-09-09",
    birthPlace: "Brus Laguna, Honduras",
    nationality: "Hondureña",
    height: "1.73 m",
    weight: "72 kg",
    preferredFoot: "Derecho",
    joinedDate: "2023-01-10",
    stats: {
      matchesPlayed: 30,
      goals: 2,
      assists: 3,
      minutesPlayed: 2510,
      yellowCards: 8,
      redCards: 0,
    },
    attributes: {
      pace: 79,
      shooting: 61,
      passing: 70,
      dribbling: 71,
      defending: 76,
      physical: 79,
    },
    bio: "Experimentado lateral derecho nacional. Aporta madurez táctica, marca ferrea y desdobles inteligentes en ofensiva. Su experiencia internacional es de gran valor para los jóvenes.",
    quote: "La experiencia me ha enseñado que los campeonatos se construyen desde la solidez de la defensa.",
  },
  {
    id: "kenny-bodden",
    name: "Kenny Bodden",
    fullName: "Kenny Bodden",
    number: 4,
    position: "Defensa",
    category: "defender",
    image: "/assets/players/kenny-bodden.webp",
    birthDate: "1999-05-12",
    birthPlace: "La Ceiba, Honduras",
    nationality: "Hondureña",
    height: "1.86 m",
    weight: "80 kg",
    preferredFoot: "Derecho",
    joinedDate: "2023-07-01",
    stats: {
      matchesPlayed: 18,
      goals: 0,
      assists: 0,
      minutesPlayed: 1350,
      yellowCards: 5,
      redCards: 1,
    },
    attributes: {
      pace: 68,
      shooting: 38,
      passing: 60,
      dribbling: 52,
      defending: 77,
      physical: 80,
    },
    bio: "Marcador central de gran fortaleza física, especialista en los duelos individuales terrestres y aéreos. Siempre concentrado en la marca.",
    quote: "El orden y la comunicación atrás son innegociables.",
  },

  // ================= Mediocampistas =================
  {
    id: "francisco-martinez",
    name: "Francisco Martínez",
    fullName: "Francisco Javier Martínez Ruíz",
    number: 8,
    position: "Mediocampista",
    category: "midfielder",
    image: "/assets/players/francisco-martinez.webp",
    birthDate: "1992-10-29",
    birthPlace: "Santa Elena, Honduras",
    nationality: "Hondureña",
    height: "1.78 m",
    weight: "74 kg",
    preferredFoot: "Derecho",
    joinedDate: "2022-08-01",
    stats: {
      matchesPlayed: 34,
      goals: 3,
      assists: 2,
      minutesPlayed: 2890,
      yellowCards: 9,
      redCards: 0,
    },
    attributes: {
      pace: 70,
      shooting: 65,
      passing: 78,
      dribbling: 70,
      defending: 81,
      physical: 85,
    },
    bio: "Popularmente conocido como 'El Chelo', su ascenso meteórico desde el fútbol amateur hasta la selección nacional y Marathón inspiró a todo el país. Es el pulmón del mediocampo, infatigable en la recuperación y con buen trato de balón.",
    quote: "Nunca dejes de creer. Con trabajo duro, humildad y fe, no hay sueños imposibles.",
  },
  {
    id: "isaac-castillo",
    name: "Isaac Castillo",
    fullName: "Isaac Edgardo Castillo Díaz",
    number: 10,
    position: "Mediocampista",
    category: "midfielder",
    image: "/assets/players/isaac-castillo.webp",
    birthDate: "2003-05-24",
    birthPlace: "San Pedro Sula, Honduras",
    nationality: "Hondureña",
    height: "1.72 m",
    weight: "66 kg",
    preferredFoot: "Derecho",
    joinedDate: "2021-01-01",
    stats: {
      matchesPlayed: 31,
      goals: 4,
      assists: 6,
      minutesPlayed: 1980,
      yellowCards: 3,
      redCards: 0,
    },
    attributes: {
      pace: 78,
      shooting: 72,
      passing: 82,
      dribbling: 84,
      defending: 55,
      physical: 62,
    },
    bio: "Una de las joyas de las fuerzas básicas del club. Mediocampista ofensivo muy creativo, con un regate en espacio corto sobresaliente y excelente visión para asistir a los delanteros.",
    quote: "Llevar la número 10 de este club histórico es un orgullo y un reto que asumo con alegría y pasión.",
  },
  {
    id: "damin-ramirez",
    name: "Damín Ramírez",
    fullName: "Damín Ramírez Arriaga",
    number: 5,
    position: "Mediocampista",
    category: "midfielder",
    image: "/assets/players/damin-ramirez.webp",
    birthDate: "1993-01-15",
    birthPlace: "Yoro, Honduras",
    nationality: "Hondureña",
    height: "1.70 m",
    weight: "69 kg",
    preferredFoot: "Derecho",
    joinedDate: "2022-06-15",
    stats: {
      matchesPlayed: 33,
      goals: 5,
      assists: 7,
      minutesPlayed: 2640,
      yellowCards: 4,
      redCards: 0,
    },
    attributes: {
      pace: 72,
      shooting: 76,
      passing: 84,
      dribbling: 78,
      defending: 64,
      physical: 70,
    },
    bio: "Mediocampista mixto de exquisita técnica y disparo de larga distancia. Se encarga de la distribución y los tiros libres. Es el metrónomo del fútbol verdolaga.",
    quote: "La precisión y la paciencia abren los cerrojos más difíciles en el campo de juego.",
  },
  {
    id: "gerson-chavez",
    name: "Gerson Chávez",
    fullName: "Gerson Aldair Chávez Suazo",
    number: 6,
    position: "Mediocampista",
    category: "midfielder",
    image: "/assets/players/gerson-chavez.webp",
    birthDate: "2000-06-25",
    birthPlace: "La Ceiba, Honduras",
    nationality: "Hondureña",
    height: "1.80 m",
    weight: "76 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-01-10",
    stats: {
      matchesPlayed: 20,
      goals: 1,
      assists: 1,
      minutesPlayed: 1220,
      yellowCards: 6,
      redCards: 0,
    },
    attributes: {
      pace: 73,
      shooting: 55,
      passing: 70,
      dribbling: 65,
      defending: 78,
      physical: 82,
    },
    bio: "Volante de contención férreo y tácticamente disciplinado. Excelente en el repliegue y coberturas defensivas, proporcionando equilibrio al mediocampo.",
    quote: "El trabajo sucio es el que permite que los de arriba brillen libremente.",
  },

  // ================= Delanteros =================
  {
    id: "alexy-vega",
    name: "Alexy Vega",
    fullName: "Alexy Noel Vega Orellana",
    number: 7,
    position: "Delantero",
    category: "forward",
    image: "/assets/players/alexy-vega.webp",
    birthDate: "1996-09-16",
    birthPlace: "Jutiapa, Honduras",
    nationality: "Hondureña",
    height: "1.75 m",
    weight: "70 kg",
    preferredFoot: "Izquierdo",
    joinedDate: "2024-01-01",
    stats: {
      matchesPlayed: 35,
      goals: 18,
      assists: 9,
      minutesPlayed: 2950,
      yellowCards: 5,
      redCards: 0,
    },
    attributes: {
      pace: 88,
      shooting: 86,
      passing: 80,
      dribbling: 85,
      defending: 42,
      physical: 74,
    },
    bio: "Extremo desequilibrante con un disparo temible de pierna zurda y gran capacidad goleadora. Nombrado jugador de la temporada tras guiar al equipo ofensivamente con goles de tiro libre, larga distancia y jugadas individuales.",
    quote: "Tomo el balón pensando en la portería. La alegría del gol es lo que nos mueve cada fin de semana.",
  },
  {
    id: "clayvin-zuniga",
    name: "Clayvin Zúniga",
    fullName: "Clayvin Julián Zúniga Bernárdez",
    number: 9,
    position: "Delantero",
    category: "forward",
    image: "/assets/players/clayvin-zuniga.webp",
    birthDate: "1991-03-29",
    birthPlace: "Limón, Honduras",
    nationality: "Hondureña",
    height: "1.80 m",
    weight: "79 kg",
    preferredFoot: "Derecho",
    joinedDate: "2022-06-20",
    stats: {
      matchesPlayed: 32,
      goals: 12,
      assists: 3,
      minutesPlayed: 2210,
      yellowCards: 3,
      redCards: 0,
    },
    attributes: {
      pace: 78,
      shooting: 82,
      passing: 68,
      dribbling: 74,
      defending: 48,
      physical: 83,
    },
    bio: "Delantero centro potente, goleador y muy hábil protegiendo el balón de espaldas al marco. Un referente ofensivo experimentado del equipo, con olfato goleador nato.",
    quote: "Dentro del área hay que tener frialdad. Un segundo de desconcentración del rival y es gol.",
  },
  {
    id: "juan-anangono",
    name: "Juan Anangonó",
    fullName: "Juan Luis Anangonó León",
    number: 21,
    position: "Delantero",
    category: "forward",
    image: "/assets/players/juan-anangono.webp",
    birthDate: "1989-04-13",
    birthPlace: "Ibarra, Ecuador",
    nationality: "Ecuatoriana",
    height: "1.87 m",
    weight: "85 kg",
    preferredFoot: "Derecho",
    joinedDate: "2024-06-15",
    stats: {
      matchesPlayed: 15,
      goals: 6,
      assists: 2,
      minutesPlayed: 980,
      yellowCards: 2,
      redCards: 0,
    },
    attributes: {
      pace: 70,
      shooting: 80,
      passing: 65,
      dribbling: 70,
      defending: 40,
      physical: 88,
    },
    bio: "Puntero central ecuatoriano de dilatada y exitosa trayectoria internacional. Famoso por su implacable remate de cabeza y juego físico para fijar defensas rivales.",
    quote: "He venido a aportar goles, sacrificio y experiencia para poner a Marathón en lo más alto.",
  },
  {
    id: "junior-lacayo",
    name: "Junior Lacayo",
    fullName: "Junior Alberto Lacayo Rochez",
    number: 18,
    position: "Delantero",
    category: "forward",
    image: "/assets/players/junior-lacayo.webp",
    birthDate: "1995-08-19",
    birthPlace: "La Ceiba, Honduras",
    nationality: "Hondureña",
    height: "1.66 m",
    weight: "63 kg",
    preferredFoot: "Derecho",
    joinedDate: "2023-06-25",
    stats: {
      matchesPlayed: 25,
      goals: 4,
      assists: 3,
      minutesPlayed: 1040,
      yellowCards: 1,
      redCards: 0,
    },
    attributes: {
      pace: 87,
      shooting: 73,
      passing: 69,
      dribbling: 80,
      defending: 38,
      physical: 60,
    },
    bio: "Extremo extremadamente rápido e impredecible. Un revulsivo de lujo capaz de romper defensas cansadas en los segundos tiempos con su cambio de ritmo.",
    quote: "La velocidad es mi mayor arma. Cuando hay espacio, voy con todo.",
  },
];

export const STAFF: StaffMember[] = [
  {
    id: "hernan-medina",
    name: "Hernán Medina",
    role: "Director Técnico",
    nationality: "Argentina",
    joinedDate: "2024-01-01",
    image: "/assets/players/hernan-medina.webp",
    bio: "Conocido como 'La Tota', el estratega cordobés llegó para plasmar una identidad de juego ofensiva, intensa y dinámica. Subcampeón con el club en su primer torneo, busca consolidar el proyecto rumbo a la décima copa.",
  },
  {
    id: "leonardo-torres",
    name: "Leonardo Torres",
    role: "Asistente Técnico",
    nationality: "Argentina",
    joinedDate: "2024-01-01",
    bio: "Mano derecha del Director Técnico, encargado del análisis táctico de los rivales y de planificar el trabajo táctico diario.",
  },
  {
    id: "juan-obelar",
    name: "Juan Obelar",
    role: "Preparador de Porteros",
    nationality: "Uruguaya",
    joinedDate: "2023-06-01",
    bio: "Ex-guardameta histórico de Marathón y muy querido por la afición. Hoy vuelca su experiencia preparando al máximo nivel a César Samudio y los jóvenes del arco verdolaga.",
  },
];
